import { readFileSync } from "fs";
import { resolve } from "path";
import { describe, expect, it } from "vitest";

import { decodeBinaryFrame, rowText } from "../canvasTerminalUtils";

/**
 * Cross-language golden-byte fixture (color-tools plan, Phase 0).
 *
 * Every other frame-decoding test in this directory hand-builds bytes against
 * the wire format *as documented* in `serialize_dirty_rows`'s doc comment
 * (`src-tauri/src/terminal_grid.rs`) — including `frameFixture.ts`'s own
 * docblock, which says so explicitly. That means the Rust encoder and this
 * TS decoder have only ever been tested independently against a shared
 * *written* spec, never against a shared *generated* artifact. A
 * synchronized-but-wrong change to both sides (e.g. both flip an offset the
 * same wrong way) would pass every existing test on both sides.
 *
 * This fixture closes that gap: `golden_frame.bin` is real output from
 * `TerminalGrid::serialize_dirty_rows()` for a small, deterministic 2x4 grid
 * ("Hi" in a 24-bit fg color), generated by a Rust test
 * (`terminal_grid::tests::regenerate_golden_frame_fixture`, `#[ignore]`d) and
 * checked in under `src-tauri/src/fixtures/frame_protocol/`. A sibling Rust
 * test (`golden_frame_fixture_matches_current_encoder_output`) asserts the
 * live encoder still reproduces these exact bytes. If the wire format ever
 * changes intentionally, regenerate the fixture and update this test's
 * expectations in the same commit — see that Rust test's doc comment.
 */
const GOLDEN_FIXTURE_PATH = resolve(__dirname, "../../../../src-tauri/src/fixtures/frame_protocol/golden_frame.bin");

function loadGoldenFrameBuffer(): ArrayBuffer {
	const buf = readFileSync(GOLDEN_FIXTURE_PATH);
	return buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength) as ArrayBuffer;
}

describe("golden cross-language frame fixture", () => {
	it("decodes the real Rust-encoded fixture with the expected header fields", () => {
		const frame = decodeBinaryFrame(loadGoldenFrameBuffer());
		expect(frame).not.toBeNull();
		if (!frame) return;

		expect(frame.screenRows).toBe(2);
		expect(frame.screenCols).toBe(4);
		expect(frame.cursorRow).toBe(0);
		expect(frame.cursorCol).toBe(2);
		expect(frame.cursorVisible).toBe(true);
		expect(frame.displayOffset).toBe(0);
		expect(frame.historySize).toBe(0);
		expect(frame.historyBase).toBe(0);
		expect(frame.hasSelection).toBe(false);
	});

	it("decodes row 0's text and 24-bit fg color exactly as the Rust source wrote them", () => {
		const frame = decodeBinaryFrame(loadGoldenFrameBuffer());
		expect(frame).not.toBeNull();
		if (!frame) return;

		const row0 = frame.rows.find((r) => r.index === 0);
		expect(row0).toBeDefined();
		if (!row0) return;

		// "Hi" written via `\x1b[38;2;100;150;200mHi\x1b[0m` into a 4-col row —
		// the trailing two cells are blank (codepoint 0 -> space, per rowText()).
		expect(rowText(row0)).toBe("Hi  ");

		const packedFg = (100 << 16) | (150 << 8) | 200;
		expect(row0.fg[0]).toBe(packedFg);
		expect(row0.fg[1]).toBe(packedFg);
	});
});
