# /// script
# requires-python = ">=3.11"
# dependencies = ["huggingface_hub"]
# ///
"""Generate `src-tauri/crates/tuic-dictation/src/speech/assets_voices.rs`.

Plan `plans/pocket-voices-and-loudness.md`, Step 2. Every downloadable voice
is pinned to a URL at an immutable revision and a sha256. The sha256 and the
size come from Hugging Face (`paths-info`, the LFS object id of each file) at
that revision, never from a person typing them.

A language's shipped default voice is already part of the language payload in
`assets.rs`. It is not repeated here. The script checks that the default in
`assets.rs` is pinned to the same revision, sha256 and size that Hugging Face
reports, and fails if it is not.

Voices that `scripts/speech-assets/verify_voices.py` has not rendered must not
be added: run the gate first, with the same revisions.

Usage:

    uv run scripts/speech-assets/gen_voice_catalogue.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

from huggingface_hub import HfApi

from pins import INSTALLED_AS, VOICES_PER_LANGUAGE
from pins import VOICES_REPO as REPO
from pins import VOICES_REVISIONS as REVISIONS

ROOT = Path(__file__).resolve().parents[2]
ASSETS = ROOT / "src-tauri/crates/tuic-dictation/src/speech/assets.rs"
OUTPUT = ROOT / "src-tauri/crates/tuic-dictation/src/speech/assets_voices.rs"



def pinned_defaults() -> dict[str, tuple[str, str, int]]:
    """The default voice of each language in `assets.rs`: (voice, sha256, size)."""
    source = ASSETS.read_text()
    pattern = re.compile(
        r'url: voice_url!\("(?P<language>[^"]+)", "(?P<voice>[^"]+)"\),\s*'
        r'sha256: "(?P<sha>[0-9a-f]{64})",\s*'
        r"size_bytes: (?P<size>[0-9_]+),"
    )
    found = {
        match["language"]: (match["voice"], match["sha"], int(match["size"].replace("_", "")))
        for match in pattern.finditer(source)
    }
    if set(found) != set(REVISIONS):
        raise SystemExit(f"default voices in assets.rs: {sorted(found)}; expected {sorted(REVISIONS)}")
    return found


def voices_at(api: HfApi, language: str) -> list[tuple[str, str, int]]:
    """Every voice of a language at its revision: (voice, sha256, size)."""
    revision = REVISIONS[language]
    folder = f"languages/{language}/embeddings"
    names = sorted(
        entry.path
        for entry in api.list_repo_tree(REPO, path_in_repo=folder, revision=revision)
        if entry.path.endswith(".safetensors")
    )
    if len(names) != VOICES_PER_LANGUAGE:
        raise SystemExit(f"{language}@{revision[:8]}: {len(names)} voices, expected {VOICES_PER_LANGUAGE}")
    out = []
    for info in api.get_paths_info(REPO, names, revision=revision):
        if info.lfs is None:
            raise SystemExit(f"{info.path} has no LFS object, so no sha256 to pin")
        out.append((Path(info.path).stem, info.lfs.sha256, info.size))
    return sorted(out)


def rust_entry(upstream: str, voice: str, sha: str, size: int) -> str:
    installed = INSTALLED_AS.get(upstream, upstream)
    return f'    voice!("{installed}", "{upstream}", "{voice}", "{sha}", {size:_}),'


def main() -> int:
    api = HfApi()
    defaults = pinned_defaults()
    lines = [
        "// @generated by scripts/speech-assets/gen_voice_catalogue.py — DO NOT EDIT.",
        "//",
        "// Every downloadable Pocket TTS voice, pinned to a revision and a sha256",
        "// read from Hugging Face. Regenerate with:",
        "//     uv run scripts/speech-assets/gen_voice_catalogue.py",
        "// A language's default voice is in its payload in `assets.rs`, not here.",
        "//",
        "// Revisions (`voice_revision!` in `assets.rs` must agree):",
    ]
    lines += [f"//   {language}: {revision}" for language, revision in REVISIONS.items()]
    lines += ["", "pub(super) static VOICES: &[Asset] = &["]

    count = 0
    for language in REVISIONS:
        default_voice, default_sha, default_size = defaults[language]
        voices = voices_at(api, language)
        by_name = {voice: (sha, size) for voice, sha, size in voices}
        if by_name.get(default_voice) != (default_sha, default_size):
            print(
                f"FAIL {language}/{default_voice}: assets.rs pins {default_sha[:12]}… {default_size}, "
                f"{REVISIONS[language][:8]} has {by_name.get(default_voice)}",
                file=sys.stderr,
            )
            return 1
        for voice, sha, size in voices:
            if voice == default_voice:
                continue
            lines.append(rust_entry(language, voice, sha, size))
            count += 1
    lines += ["];", ""]

    OUTPUT.write_text("\n".join(lines))
    print(f"wrote {count} voices to {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
